# weread2flomo 配置文件

# ==================== 基础配置 ====================

# 同步设置（默认值）
sync:
  # 只同步最近X天的划线（0表示同步所有）
  days_limit: 300

  # 每次同步的最大划线数
  max_highlights_per_sync: 10

  # 是否同步笔记（除了划线）
  sync_reviews: true

# ==================== 模板配置 ====================

# 默认使用的模板名称
# 可选值: simple, detailed, standard
default_template: detailed

# 模板定义
templates:
  # 模板1: 简洁模板（划线为主）
  simple:
    name: "简洁模板"
    description: "适合快速记录，划线内容为主"
    format: |
      {highlight_text}

      📖 《{book_title}》· {author}

      {chapter_info}

      {ai_summary_section}{tags}

  # 模板2: 标准模板（均衡）
  standard:
    name: "标准模板"
    description: "标准格式，包含完整信息"
    format: |
      📖 《{book_title}》- {author}

      > {highlight_text}

      {chapter_info}
      🔗 {book_url}

      {ai_summary_section}{note_section}{tags}

  # 模板3: 详细模板（最完整）
  detailed:
    name: "详细模板"
    description: "包含所有元数据，适合深度阅读"
    format: |
      {highlight_text}

      📚 来源：《{book_title}》· {author}

      📂 章节：{chapter_info}

      📅 时间：{create_time}

      {ai_summary_section}{note_section}{tags}

# ==================== 标签配置 ====================
# 注意：敏感信息（AI_API_KEY）在 .env 文件中配置
# 其他标签配置直接在此处修改即可

tags:
  # 默认标签（总是添加，仅在非层级模式下使用）
  default:
    - "#微信读书"

  # 是否使用层级标签（flomo 层级标签功能）
  # true: #微信读书/书名（推荐，更好的组织结构）
  # false: #微信读书 #书名（独立标签）
  use_hierarchical_tags: true

  # 是否添加书名作为标签
  add_book_title: true

  # 是否添加作者作为标签
  add_author: false

  # 是否启用AI自动标签
  enable_ai_tags: flase

  # AI标签的最大数量
  max_ai_tags: 3

# ==================== 书籍分类配置 ====================

book_categories:
  # 工作类书籍关键词和标签
  work:
    keywords:
      - "管理"
      - "领导力"
      - "商业"
      - "职场"
      - "创业"
      - "营销"
      - "沟通"
      - "效率"
      - "时间管理"
    tags:
      - "#工作"
      - "#职场"
    template: "standard"

  # 个人成长类
  growth:
    keywords:
      - "思维"
      - "心理"
      - "习惯"
      - "成长"
      - "认知"
      - "学习"
      - "自律"
    tags:
      - "#个人成长"
      - "#自我提升"
    template: "standard"

  # 文学类
  literature:
    keywords:
      - "小说"
      - "散文"
      - "诗歌"
      - "文学"
      - "故事"
    tags:
      - "#文学"
      - "#阅读"
    template: "simple"

  # 技术类
  tech:
    keywords:
      - "编程"
      - "技术"
      - "算法"
      - "设计模式"
      - "架构"
      - "代码"
      - "开发"
    tags:
      - "#技术"
      - "#编程"
    template: "detailed"

# ==================== AI 配置 ====================
# 注意：只有 AI_API_KEY 在 .env 文件中配置（敏感信息）
# 其他 AI 配置直接在此处修改即可

ai:
  # AI 服务提供商
  # openai - OpenAI 或兼容格式的 API
  # local - 使用本地关键词匹配规则
  # none - 不使用 AI 标签
  provider: openai

  # AI API Base URL（支持所有 OpenAI 兼容的服务）
  # OpenAI 官方: https://api.openai.com/v1
  # 国内服务: 根据服务商文档填写
  # 本地模型: http://localhost:11434/v1
  api_base: https://yunwu.ai/v1

  # AI 模型名称
  model: gpt-4.1

  # AI 摘要功能（为长划线生成一句话概述）
  enable_summary: true
  
  # 触发摘要的最小字符数（少于此长度不生成摘要）
  summary_min_length: 80  # 降低到 50 字符，让更多划线可以生成摘要

  # AI标签生成的提示词
  tag_prompt: |
    请为以下书籍划线内容生成1-3个主题标签。
    要求：
    1. 标签要简洁、准确，体现核心主题
    2. 优先使用中文
    3. 每个标签以#开头
    4. 只返回标签，不要其他内容

    书名：{book_title}
    作者：{author}
    划线：{highlight_text}

    标签：

  # AI摘要生成的提示词（P2功能）
  summary_prompt: |
    角色 Role】

    你是一位精通叙事艺术的内容策划大师，深谙人性和情感触发机制。你擅长用最简洁的语言制造"不得不去挠的瘙痒感"——那种让人忍不住想了解更多的强烈好奇心。
    【任务 Task】

    请为用户提供的内容创作一句话概述。内容可能是：

    - 电影、剧集、纪录片等影视作品

    - 书籍、文章、长文本

    - 事件、新闻、故事

    - 概念、理论、主题

    - 或任何其他需要概述的内容
    **核心原则：情感优先**

    这句话必须在情感上抓住读者，制造一种"不得不去挠的瘙痒感"。
    **必备四要素：**
    1. **反讽 (Irony)**

    揭示情境中的矛盾、反差或意外转折

    例：新婚夫妇本应甜蜜二人世界，却要疲于奔命应付四个家庭
    2. **具体性 (Specificity)**

    使用具体的细节、数字、场景，而非抽象概念

    例：不说"家庭聚会"，而说"跑遍四个再婚家庭"
    3. **冲突张力 (Conflict)**

    明确展现核心矛盾、困境或危机

    例："有个人想杀他"——生死攸关的威胁
    4. **情感钩子 (Emotional Hook)**

    触发共鸣、好奇、恐惧、惊讶等强烈情感

    例：度假本应放松，却变成生存游戏
    **其他要求：**

    - 使用简洁、口语化、画面感强的表达

    - 长度控制在20-50字之间

    - 避免陈词滥调和说教式语言

    - 保持客观准确，不夸大不误导
    【格式 Format】

    根据内容类型，采用相应格式输出：
    **影视作品：**

    [一句话概述]——《[中文名]》([英文名/原名])
    **书籍：**

    [一句话概述]——《[书名]》，[作者]
    **文本/文章：**

    [一句话概述]——[来源/标题]
    **事件/概念/其他：**

    [一句话概述]——[名称/主题]
    **如果用户直接提供大段文本：**

    [一句话概述]
    【示例分析 Examples】
    **示例1：**

    一对新婚夫妇要在圣诞节这天跑遍双方父母的四个再婚家庭。——《四个圣诞节》(Four Christmases)
    ✓ 反讽：新婚应该浪漫，却要疲于应付家庭

    ✓ 具体性："四个"家庭、"圣诞节这天"

    ✓ 冲突：时间紧迫 vs 多个家庭的期待

    ✓ 情感：共鸣（谁没经历过节日家庭压力？）
    **示例2：**

    一个新入职的员工去参加公司的周末集体度假，结果发现有个人想杀他。——《度假》(The Retreat)
    ✓ 反讽：团建度假本应轻松，却变成生死危机

    ✓ 具体性："新入职"、"周末集体度假"

    ✓ 冲突：生存威胁 vs 无法逃离的社交场合

    ✓ 情感：恐惧+好奇（为什么？是谁？）
    **更多示例：**
    一个失忆的杀手醒来发现，自己要杀的目标竟是三天前的自己。——《记忆迷局》(示例)

    ✓ 反讽：杀手 vs 自己

    ✓ 具体性："三天前"

    ✓ 冲突：身份悖论

    ✓ 情感：困惑+惊悚
    她花了十年成为顶级律师，只为合法地毁掉当年欺负她的人。——《黑暗正义》(示例)

    ✓ 反讽：用法律实现复仇

    ✓ 具体性："十年"、"顶级律师"

    ✓ 冲突：正义 vs 复仇

    ✓ 情感：共鸣+期待
    一位AI伦理学家发现，自己研究了五年的"人类"同事其实是AI。——《图灵悖论》(示例)

    ✓ 反讽：研究AI的专家被AI欺骗

    ✓ 具体性："五年"、"同事"

    ✓ 冲突：专业身份的崩塌

    ✓ 情感：震惊+质疑现实

    请概述：{highlight_text}

# ==================== 高级选项 ====================

advanced:
  # 是否在同步前备份
  backup_before_sync: true

  # 日志级别: DEBUG, INFO, WARNING, ERROR
  log_level: "INFO"

  # 请求延迟（秒）
  request_delay: 1.0

  # 重试次数
  max_retries: 3
